return failure if called from an incorrect pam stack
Signed-off-by: Gregory Bartholomew <gregory.lee.bartholomew@gmail.com>

diff --git a/homelock b/homelock
--- a/homelock
+++ b/homelock
@@ -197,6 +197,12 @@ case "$PAM_TYPE" in
       note "zfs pool $(bold $POOL) exported"
     fi
   ;;
+  (open_session)
+    exit 0
+  ;;
+  (*)
+    # return failure if homelock is called from any pam stack other than the
+    # ones handled in the above cases
+    exit 1
+  ;;
 esac
-
-exit 0
